### PR TITLE
Update LINKSWAP Adapter

### PR DESCRIPTION
**Pull request by giovannidisiena**
This PR adds an update to the adapter for the YF Link community-governed AMM LINKSWAP.

The adapter now includes the new `sYFL` pools and may need further updates when either `bYFL` goes live or a new factory contract may be deployed for `RugLock`.

### CODE REVIEW

**Comment by sobolev-igor** [comment]
hi @giovannidisiena is update for this adapter live? Should we add this version of the adapter or should we wait for bYFL or new factory contract?

**Comment by giovannidisiena** [comment]
Hi @sobolev-igor , yes this is all fine to go live now as there are no further updates at this time:)

**Comment by sobolev-igor** [comment]
Hi, I've noticed a bug after I merged the PR -- 0x603065B7e2F69c897F154Ca429a2B96Cf4703f56 address repeats twice. Could you please recheck addresses and open a PR with a fix?
Снимок экрана 2021-02-11 в 12 49 22

**Comment by giovannidisiena** [comment]
Thanks for picking up on this @sobolev-igor , should be fixed in #144 .

**Pull request merged**
