### PR TITLE
Fix link-yax pool address

### PR DESCRIPTION
**Pull request by giovannidisiena**
This PR fixes the LINK-YAX pool address as per the comment in #139.

### CODE REVIEW

**Comment by sobolev-igor** [comment]
I've applied fix in the master branch and fixed tests so it could pass, however, the test for **LinkswapStakingAdapter** fails with revert and code for pools is not verified, so I cannot debug it. Could you please take a look?

**Comment by giovannidisiena** [comment]
Sorry, I am not sure about this. I looked to the other StakingAdapter tests for an indication and this one is the same as far as I can tell, so I do not know why it is failing.

**Comment by sobolev-igor** [comment]
This might happen if some of the contracts do not have the function which is called from the adapter, e.g. `earned(address, uint256)`, may be `earned(address)` is used instead, idk...

**Comment by giovannidisiena** [comment]
As far as I can tell, they should all have the first instance of the earned function signature you reference though I noticed this contract for the LINK-YAX pool is not verified https://etherscan.io/address/0xf4C17025B623665AAcAb958FC0fa454b1265A219#code so maybe that is why?

**Comment by sobolev-igor** [comment]
the code may be found here https://etherscan.io/address/0x22aebd24d0a9f74a84422ee6904e146d61dc3b70#code as the StakingRewards contracts are deployed via factory.

However, at least this contract `LSLP_LINK_YFLUSD_POOL = 0x61401c19200B2420f93Bb2EECF4BAA2C193d76e1;` 
has the second type of `earned` function (with the only `address` argument). Please fix the code and make sure the tests pass (you can add some more to make sure all pools are working).

**Comment by giovannidisiena** [comment]
Ah I see, thanks very much for pointing this out! Yes, the `YFLUSD` pools are all causing the issue due to being of the second type.

**Comment by giovannidisiena** [comment]
@sobolev-igor how is that looking to you now?

**Comment by sobolev-igor** [comment]
Please merge current `master` branch into yours, currently contracts are not compiling, I've fixed it there)

**Comment by sobolev-igor** [comment]
tests are still failing, please fix the adapter code!

**Comment by giovannidisiena** [comment]
@sobolev-igor I have been trying to compile and test locally in order to resolve this without repeatedly pushing failing tests but get this error: ```ParserError: Source file requires different compiler version (current compiler is 0.5.16+commit.9c3226ce.Emscripten.clang```. I have tried making changes to `package.json` and `truffle.js` but it still does not work - do I need to change the solidity version in the contracts, or somewhere else instead?

**Comment by sobolev-igor** [comment]
wow, seems like it's trying to use some cached version of solidity which is old one

how do you run tests? try removing `node_modules` directory and running `npm install` + `npm run test` without any changes to `package.json` and `truffle.js`

**Comment by giovannidisiena** [comment]
Haha okay, that is strange! I’ve just been running `npm install` and `npm run compile` but will try that and let you know...

**Comment by giovannidisiena** [comment]
@sobolev-igor I’m seeing an error thrown after the script starts ganache instance `Cannot find module `.../node_modules/.bin/truffle` which I can see was installed by `npm install` initially with `@truffle` directory in `node_modules`, tried installing manually as well but was still getting this error. I also altered the path in `scripts/test.sh` by removing `.bin` but that doesn’t seem to have worked either... Any ideas?

**Comment by sobolev-igor** [comment]
May be it has conflicts with globally installed version 🤔, try removing global version of `truffle` (if it exists), try updating `npm` and `npx` (it should be installed together with `npm`). Try also reinstalling the packages with removed `package-lock.json` file

**Comment by giovannidisiena** [comment]
Tried that, now getting `unable to resolve dependency tree` after which I tried `npm install —legacy-peer-deps` but still getting `git dep preparation failed`. I assume this is an issue of mine locally, though it obviously makes difficult to test any changes. Thanks for your help with this so far. Do you have any other ideas? Npm version? I’m using `7.5.4` for reference.

**Comment by sobolev-igor** [comment]
you can try setting up github actions (copy `.github` directory from `master` branch and run tests in the actions). You will also need to setup secrets in project settings.

**Comment by giovannidisiena** [comment]
Thanks, I’ve been busy with my degree this week but will take a look over the weekend and try that out:+1

**Comment by giovannidisiena** [comment]
Lowering the node version seemed to work for the install, though now I'm seeing this error:

```Error: There was a timeout while attempting to connect to the network. Check to see that your provider is valid. If you have a slow internet connection, try configuring a longer timeout in your Truffle config. Use the networks[networkName].networkCheckTimeout property to do this. at Timeout.setTimeout (.../defi-sdk/node_modules/truffle/build/webpack:/packages/provider/index.js:56:1)```

but cannot find that file it points to even after setting all the variables in `.env`. Since I seem to be spending a lot of time trying to get this working to no avail and is likely a small fix, have you got a test output I could look at please, to point me in the right direction?

**Comment by sobolevigor986** [comment]
https://github.com/zeriontech/defi-sdk/runs/1902276631?check_suite_focus=true

This is the test output with your tests enabled. The problem that some contracts that have `earned()` function with 1 param are called as `earned()` with 2 params, thus the whole tx fails without even proper error code, just `revert`. You should check it more accurate.

**Comment by giovannidisiena** [comment]
Okay, I think I figured out what the issue is actually. It doesn't seem to be a problem with the `earned()` signatures but rather some of the pool (which are inactive now) come under a different contract which doesn't actually have this function implemented. So I've asked the team if there is any other way of retrieving the rewards earned for these expired pools, but if not or if easier we can just remove these from the adapter and that should fix it.

**Comment by giovannidisiena** [comment]
And on further inspection it looks as though these may have also been mistakenly listed under the LP token variables rather than pools. Will aim to have it fixed by EOD tomorrow.

**Comment by giovannidisiena** [comment]
@sobolev-igor I have checked through everything else in `LinkswapStakingAdapter` and it all seems okay now. I also noticed you made changes to the tests and commented out a lot - what's happening with those now? Shall I go back through and check the tests are correct, before adding them back in, or have you got that handled?

**Comment by sobolev-igor** [comment]
Hi, please do not uncomment the commented part (actually, they can be removed)

You can try running tests with all the staked tokens replacing `yflAddress` with other tokens' addresses at line 68:
https://github.com/zeriontech/defi-sdk/blob/master/test/LinkswapStakingAdapter.js#L68

**Comment by giovannidisiena** [comment]
Again, apologies for the delay in getting to this - lots of deadlines coming up! Let me know how the tests are looking now (still can't test locally or with GH actions but hoping that should all be okay 🤞).

**Pull request closed without merging**
